.TH "pcrepp" 3 "25 Aug 2004" "PCRE++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcrepp \- 
.SH SYNOPSIS
.br
.PP
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBexception\fP"
.br
.ti -1c
.RI "class \fBPcre\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PCRE++ from the source code.
