.TH "pcre++.cc" 3 "25 Aug 2004" "PCRE++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcre++.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'pcre++.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PCRE++ from the source code.
